name: Check 
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
            