name: Backend Lint 
on:
  push:
    paths:
      - 'actor_based_chat/backend/**'
  pull_request:
    paths:
      - 'actor_based_chat/backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
            
